### ISSUE TITLE
request demo link

### ISSUE THREAD

**Issue by JustQY** [touchgfx/4.22.touchgfx.github.io#2]
![snap_screen_20230731084103](https://github.com/touchgfx/4.22.touchgfx.github.io/assets/9473678/ab8d3ac1-7b69-44a1-a5be-a34209fb8617)

where can i download this example?

**Comment by zrrbite** [comment]
![image](https://github.com/touchgfx/4.22.touchgfx.github.io/assets/1027197/f2e3ced3-b65b-48d6-8c11-60325b3b0058)

You can find it as "Unmapped Font Demo" under "Demos" in the designer.

**Comment by JustQY** [comment]
> ![image](https://user-images.githubusercontent.com/1027197/257656535-f2e3ced3-b65b-48d6-8c11-60325b3b0058.png)
> 
> You can find it as "Unmapped Font Demo" under "Demos" in the designer.

thinks,i found it finnally,must click downall in file menu
another question,
![snap_screen_20230804134902](https://github.com/touchgfx/4.22.touchgfx.github.io/assets/9473678/efaee901-c7a3-4c68-a0d1-48cd8d314127)
where is this config location?

**Comment by zrrbite** [comment]
The article is talking about additional code being generated (e.g. LCD16SerialFlash instead of LCD16 in order to provide an interface for fetching glyphs from a serial flash (unmapped), and a subclass of FlashDataReader for you to fetch from the connected serial flash.

You can find a fully functional configuration/code in that demo I'm pretty sure. Look for the FlashDataReader in the source code. So, if you combine the "Unmapped font demo" with a board package like "STM32G071":

![image](https://github.com/touchgfx/4.22.touchgfx.github.io/assets/1027197/4e5eab94-348d-4a29-9e7a-929d46a8f2a9)

You'll have a flashdatareader all ready to go. Pretty sure the demo should just work:

![image](https://github.com/touchgfx/4.22.touchgfx.github.io/assets/1027197/eb346e2a-1571-405d-b2ae-0f3166f9e429)
